# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

EXPOSE 8080

LABEL io.openshift.expose-services="8080:http"

RUN chgrp -R 0 /var/log/httpd /var/run/httpd && _
    chmod -R g=u /var/log/httpd /var/run/httpd

USER 1001
